version: "3.7"
services:
  cli: &cli
    build: .
    command: python cli.py dashboard
    working_dir: /usr/src/app/
    environment:
      - DEBUG=true
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - "./:/usr/src/app/"
    stdin_open: true
    tty: true

  isort:
    <<: *cli
    command: isort .

  black:
    <<: *cli
    command: black --line-length 88 --check .

  flake8:
    <<: *cli
    command: flake8 .

  mypy:
    <<: *cli
    command: mypy . --ignore-missing-imports

  pylint:
    <<: *cli
    command: pylint --rcfile=.pylintrc .

  test:
    <<: *cli
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN-"token"}
    command: pytest -cov=reviews -cov-report -vvv
